{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: flow-pipe-api
  namespace: {{ include "flowpipe.namespace" . }}
spec:
  type: {{ .Values.api.httpService.type | default "ClusterIP" }}
  selector:
    app: flow-pipe-api
  ports:
    - name: http
      port: {{ .Values.api.httpPort }}
      targetPort: http
      protocol: TCP

    - name: grpc
      port: {{ .Values.api.grpcPort }}
      targetPort: grpc
      protocol: TCP
{{- end }}
