{{- if and .Values.api.enabled .Values.api.auth.enabled .Values.api.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.auth.secretName }}
  namespace: {{ include "flowpipe.namespace" . }}
type: Opaque
stringData:
  {{ .Values.api.auth.secretKey }}: {{ .Values.api.auth.apiKey | quote }}
{{- end }}
