{{- if and .Values.api.enabled .Values.api.grpcService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: flow-pipe-api-grpc
  namespace: {{ include "flowpipe.namespace" . }}
  {{- with .Values.api.grpcService.annotations }}
  annotations:
  {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.grpcService.type | default "LoadBalancer" }}
  selector:
    app: flow-pipe-api
  ports:
    - name: grpc
      port: {{ .Values.api.grpcPort }}
      targetPort: grpc
      protocol: TCP
{{- end }}
