{{- if and .Values.api.enabled .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flow-pipe-api
  namespace: {{ include "flowpipe.namespace" . }}
  annotations:
    {{- with .Values.api.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
spec:
  {{- if .Values.api.ingress.className }}
  ingressClassName: {{ .Values.api.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.api.ingress.host }}
      http:
        paths:
          - path: {{ .Values.api.ingress.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: flow-pipe-api
                port:
                  number: {{ .Values.api.port }}
  {{- if .Values.api.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.api.ingress.host }}
      secretName: {{ .Values.api.ingress.tls.secretName }}
  {{- end }}
{{- end }}
