apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-pipe-controller
  namespace: {{ include "flowpipe.namespace" . }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app: flow-pipe-controller
  template:
    metadata:
      labels:
        app: flow-pipe-controller
    spec:
      serviceAccountName: flow-pipe-controller
      containers:
        - name: controller
          image: {{ .Values.controller.image }}
          imagePullPolicy: {{ .Values.controller.imagePullPolicy | default "IfNotPresent" }}
          env:
            - name: FLOW_OBSERVABILITY_ENABLED
              value: {{ .Values.observability.enabled | quote }}
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.controller.serviceName | quote }}
            {{- if .Values.observability.enabled }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.observability.exporterOtlpGrpcEndpoint | quote }}
            {{- end }}

            - name: ETCD_ENDPOINTS
              value: {{ join "," .Values.etcd.endpoints | quote }}
            - name: FLOW_CONTROLLER_WORKER_COUNT
              value: {{ .Values.controller.workerCount | quote }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
