{{- $alloyEndpoint := include "flow-pipe.alloy.otlp.endpoint" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-pipe-controller
  namespace: {{ include "flowpipe.namespace" . }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app: flow-pipe-controller
  template:
    metadata:
      labels:
        app: flow-pipe-controller
    spec:
      serviceAccountName: flow-pipe-controller
      containers:
        - name: controller
          image: {{ .Values.controller.image }}
          imagePullPolicy: {{ .Values.controller.imagePullPolicy | default "IfNotPresent" }}
          env:
            {{- if $alloyEndpoint }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ $alloyEndpoint | quote }}
            {{- end }}
            - name: ETCD_ENDPOINTS
              value: {{ join "," .Values.etcd.endpoints | quote }}
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
