{{- if and .Values.etcd.enabled .Values.etcd.monitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flow-pipe-etcd
  namespace: {{ include "flowpipe.namespace" . }}
  {{- with .Values.etcd.monitor.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ include "flowpipe.namespace" . }}
  selector:
    matchLabels:
      app: flow-pipe-etcd
      flowpipe.etcd.service: {{ ternary "headless" "client" .Values.etcd.ha.enabled | quote }}
  endpoints:
    - port: client
      path: /metrics
      interval: {{ .Values.etcd.monitor.interval | default "30s" | quote }}
      scrapeTimeout: {{ .Values.etcd.monitor.scrapeTimeout | default "10s" | quote }}
{{- end }}
