apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flow-pipe
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/hurdad/flow-pipe.git
    targetRevision: main
    path: deploy/helm/flow-pipe
    helm:
      releaseName: flow-pipe
      values: |
        api:
          enabled: true
          replicas: 1
          ingress:
            enabled: true
            className: traefik
            host: flow-pipe.k3s.lan
            tls:
              enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: flow-pipe

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
