apiVersion: v2
name: flow-pipe
description: Kubernetes-native pipeline runtime (controller + API)
type: application
version: 0.3.3
appVersion: "0.1.0"

dependencies:
  - name: prometheus
    version: 28.0.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: observability.prometheus.enabled
  - name: loki
    version: 6.49.0
    repository: https://grafana.github.io/helm-charts
    condition: observability.loki.enabled
  - name: tempo
    version: 1.24.1
    repository: https://grafana.github.io/helm-charts
    condition: observability.tempo.enabled
  - name: grafana
    version: 10.5.1
    repository: https://grafana.github.io/helm-charts
    condition: observability.grafana.enabled
  - name: alloy
    version: ">=0.0.0"
    repository: https://grafana.github.io/helm-charts
    condition: observability.alloy.enabled
